[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "debug"
DEFMT_LOG = "debug,sntpc_net_embassy=info"

[build]
rustflags = [
    # "-C", "link-arg=-Tlinkall.x",
    # "-C", "link-arg=--nmagic",

    # NOTE: May negatively impact performance of produced code
    # Required to obtain backtrace (e.g. When using the "esp-backtrace" crate.)
    "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
