[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG="debug"

[build]
rustflags = [
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "link-arg=--nmagic",

  # Required to obtain backtrace (e.g. When using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",

  # "-C", "link-arg=-Tdefmt.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
